name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
      working-directory: ./  # Change to root directory if package-lock.json is there
    - run: npm run lint
      working-directory: ./ai-dungeon-gen
    - run: npm run build --if-present
      working-directory: ./ai-dungeon-gen
    - run: npm test
      working-directory: ./ai-dungeon-gen
